# Generated by Django 3.0.6 on 2020-08-06 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Selling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_customer', models.CharField(max_length=60, null=True)),
                ('contact_number', models.IntegerField(max_length=20, null=True)),
                ('email', models.CharField(max_length=60, null=True)),
                ('name_of_phone', models.CharField(max_length=100, null=True)),
                ('about', models.CharField(max_length=240, null=True)),
                ('ram', models.IntegerField(max_length=20, null=True)),
                ('color', models.CharField(max_length=60, null=True)),
                ('storage', models.IntegerField(max_length=60, null=True)),
                ('price', models.FloatField(max_length=40, null=True)),
                ('image1', models.ImageField(null=True, upload_to='products')),
                ('image2', models.ImageField(null=True, upload_to='products')),
                ('image3', models.ImageField(null=True, upload_to='products')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='products')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staus', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Sold', 'Sold')], max_length=60, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='selling.Selling')),
            ],
        ),
    ]
