# Generated by Django 3.0.6 on 2020-08-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selling',
            name='contact_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='selling',
            name='ram',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='selling',
            name='storage',
            field=models.IntegerField(null=True),
        ),
    ]
