# Generated by Django 3.0.6 on 2020-08-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0002_auto_20200806_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='selling',
            name='staus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Sold', 'Sold')], max_length=60, null=True),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
