# Generated by Django 3.0.6 on 2020-08-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0003_auto_20200806_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selling',
            name='staus',
        ),
        migrations.AddField(
            model_name='selling',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Sold', 'Sold')], default='Pending', max_length=60),
        ),
    ]
