# Generated by Django 3.0.6 on 2020-08-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0004_auto_20200806_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='selling',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
