# Generated by Django 3.0.6 on 2020-08-07 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0005_selling_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selling',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='selling',
            name='image4',
        ),
    ]
